// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Contract struct {
	ID           int32        `json:"id"`
	ProviderName string       `json:"provider_name"`
	DocumentUrl  string       `json:"document_url"`
	Status       string       `json:"status"`
	CreatedAt    sql.NullTime `json:"created_at"`
	IsSigned     sql.NullBool `json:"is_signed"`
	DateSigned   sql.NullTime `json:"date_signed"`
}
